### ISSUE TITLE
keď alebo kedz?

### ISSUE THREAD

**Issue by zdila** [laciKE/saral#3]
Nemá byť správne `kedz` namiesto slova `keď`? Alebo to už je spišal?

**Comment by Trsek** [comment]
kedz je správne
keď už je stredoslovensky ;o)

**Comment by laciKE** [comment]
Kedz by bolo vhodnejsie. 
Vychadzal som najma z prepisu, ktory ma @Trsek na svojej stranke. Ale ako tak na to pozeram a opat pocuvam tu humoresku, je tam toho viac.. to by vydalo aj na vacsi update Saral 2.1 :-)

Btw, @Trsek , spominana stranka nie je dostupna, prepis z nej je momentalne pristupny iba z google cache http://webcache.googleusercontent.com/search?q=cache:2gTcGW22zF0J:https://www.trsek.com/pascal/%25C5%25A0aral_-_nov%25C3%25BD_programovac%25C3%25AD_jazyk&num=1&client=ubuntu&hs=QWz&hl=sk&gl=sk&strip=0&vwsrc=0

**Comment by laciKE** [comment]
Kedze vznika dalsia implementacia [Saralu 2.0 pre JVM](https://github.com/PaulNoth/saral), ak s tym suhlasi aj @PaulNoth a ostatni diskutujuci, nechali by sme specifikaciu Saral 2.0 uz nezmenenu.
A ak bude v buducnosti zaujem a nazbiera sa viacero zmien, updatneme specifikaciu na verziu 2.1.

**Comment by laciKE** [comment]
Vzhladom na to, ze sa uz nikto nevyjadril, specifikaciu Saral 2.0 pouzivanu tymto kompilatorom uz necham nezmenenu.
