### ISSUE TITLE
Pravidlo Ta boh nezna

### ISSUE THREAD

**Issue by PaulNoth** [laciKE/saral#5]
Robím verziu [Šaral 2.0 pre JVM](https://github.com/PaulNoth/saral), ktorej implementácia vychádza z tvojej špecifikácie. Časom ju snáď dokončím.

Dostal som jeden komentár od @zdila , že existuje pravidlo *[Ta boh nezna](https://www.facebook.com/permalink.php?story_fbid=296978642511&id=433557560407)*. Neviem, kto je admin tejto stránky (cc @trsek)

Možno je to ďalší prídavok do Šaral 2.1

**Comment by zdila** [comment]
Neviem o tom, ze by info o tom pravidle bolo odomna :-)

**Comment by laciKE** [comment]
No teda, v poslednom case sa zacina o Saral zaujimat coraz viac ludi... Tesim sa, ze bude aj implementacia pre JVM.

O "Ta boh nezna" som doteraz nepocul, rovnako ani o tej FB stranke. Pozeram, ze taktiez sa tam spomina aj stvrta logicka hodnota: [Moze byc](https://www.facebook.com/permalink.php?story_fbid=329284645585&id=433557560407), na ktoru sa taktiez vztahuje pravidlo "Ta boh nezna". No vyzera to tak, ze uvedena FB stranka pouziva nekompatibilne logicke hodnoty Ano, Ne, Osal a Moze byc namiesto Pravda, Osal a Skoro Osal z povodnej nahravky.

Navyse na zaklade prispevkov o Moze byc spolu s vyssie citovanym prispevkom pre [Osal](https://www.facebook.com/permalink.php?story_fbid=296978642511&id=433557560407) vsak podla mna nastava nejednoznacnost vyhodnocovania logickeho vyrazu, pokial je v nom sucasne pouzity "Osal" aj "Moze byc" a bude nutne uplatnit pravidlo "Ta boh nezna". Kvoli pouzitu osalu by hodnota vyrazu mala byt Ne, kvoli Moze byc by mala byt vysledna hodnota Ano.

Z tohto dovodu navrhujem ostat pri sucasnej trojhodnotovej logike Saralu spolu s vyhodnocovacimi pravidlami pre Kleeneho logiku, ako je to uvedene v specifikacii pouzivanej tuto.

**Comment by Trsek** [comment]
Prosím nepoužívajme výrazyvo ako "Ta boh nezna".

**Comment by laciKE** [comment]
Tato verzia Saralu ostane v povodnej podobe, vzhladom na predchadzajuce prispevky a vyssie uvedene dovody a nejednoznacnost vyhodnocovania vyrazov tento kompilator nebude podporovat "Moze byc" ani "Ta boh nezna" a ostane pri trojhodnotovej Kleeneho logike. Kazdopadne, dakujem za rozsirenie obzorov. :-)
